// <auto-generated />
using System;
using GameStoreBeSzMátyás.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStoreBeSzMátyás.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    partial class GameStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameStoreBeSzMátyás.Models.User_entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("GameStoreBeSzMátyás.Models.VideoGame_entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VideoGame");
                });

            modelBuilder.Entity("GameStoreBeSzMátyás.Models.uservideo", b =>
                {
                    b.Property<int>("User_EntitiesId")
                        .HasColumnType("int");

                    b.Property<int>("VideoGame_EntitiesId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VideoGameId")
                        .HasColumnType("int");

                    b.HasKey("User_EntitiesId", "VideoGame_EntitiesId");

                    b.HasIndex("UserId");

                    b.HasIndex("VideoGameId");

                    b.HasIndex("VideoGame_EntitiesId");

                    b.ToTable("uservideo");
                });

            modelBuilder.Entity("GameStoreBeSzMátyás.Models.uservideo", b =>
                {
                    b.HasOne("GameStoreBeSzMátyás.Models.User_entity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStoreBeSzMátyás.Models.User_entity", null)
                        .WithMany()
                        .HasForeignKey("User_EntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStoreBeSzMátyás.Models.VideoGame_entity", "VideoGame")
                        .WithMany()
                        .HasForeignKey("VideoGameId");

                    b.HasOne("GameStoreBeSzMátyás.Models.VideoGame_entity", null)
                        .WithMany()
                        .HasForeignKey("VideoGame_EntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("VideoGame");
                });
#pragma warning restore 612, 618
        }
    }
}
